version: '2'
services:
  web:
    image: amanu/php7-apache
    volumes:
     - ./web:/var/www/html/
    links:
       - db:siompubarat
    ports:
     - "80:80"

  db:
    build: .
    container_name: siompubarat
    ports:
     - "3309:3306"
    volumes:
     - db_data:/var/lib/mysql
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: siompu123
     MYSQL_DATABASE: siompubarat

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db:siompubarat
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"

volumes:
  db_data:
